version: "3.9"

services:
  # db:
  #   image: postgres:14-alpine
  #   ports:
  #     - '5432:5432'

  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=postgres

  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/development:/etc/nginx/conf.d
    # depends_on:
    #     - backend

  # frontend:
  #   build:
#       context: ./frontend
#     dockerfile: Dockerfile

#   ports:
#     - '3000:3000'

# depends_on:
#   - backend

# backend:
#   build:
#     context: ./backend
#     dockerfile: Dockerfile

#   environment:
#     - POSTGRES_PASSWORD=postgres
#     - POSTGRES_USER=postgres
#     - POSTGRES_DB=postgres

#   ports:
#     - '8000:8000'

#   depends_on:
#     - db
