version: "3.9"

services:
  # db:
  #   image: postgres:14-alpine
  #   ports:
  #     - "5432:5432"

  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=postgres
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
      - ./frontend/node_modules:/app/frontend/node_modules
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 3001:5000
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGOUSER=user
      - MONGOPASSWORD=pass
      - MONGOHOST=mongodb
      - MONGOPORT=27017
      - MONGODATABASE=dev
      - TOKEN_SECRET=secret
      - TOKEN_EXPIRATION=1h
      - REFRESH_TOKEN_SECRET=secret
      - REFRESH_TOKEN_EXPIRATION=1d
      - AUTH=true

    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    depends_on:
      - mongodb
